config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root "products#index"
 resources :products
 resources :sessions, only: [:new, :create]
 delete "/sessions/sign_out", to: "sessions#sign_out"

 resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord 
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0.01 } 
end

app/models/user.rb
class User < ApplicationRecord 
  validates :email, :password, :confirm_password, presence: true
  validates :email, uniqueness: true
  has_many :user_products, dependent: :destroy
  has_many :products, through: :user_products
end

app/models/user_product.rb
class UserProduct  < ApplicationRecord 
  belongs_to :user
  belongs_to :product

  validates :quantity, presence: true, numericality: {greater_than_or_equal_to: 1}

  enum status: [:ordered, :delivered, :cancelled]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    session[:current_user]
  end

  def authenticate!
    redirect_to new_session_path  unless current_user.present?
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
  end

  def new 
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private 

  def order_params 
    params.require(:products).permit(:product_id, :quantity)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate!
  
  def index
    @products = Product.all 
  end

  def new 
  end

  def create
    Product.create!(product_params)
    redirect_to products_path
  end

  def edit 
    @product = Product.find(params.require(:id))
  end

  def destroy
    @product = Product.find(params.require(:id))
    @product.destroy!
    redirect_to products_path
  end

private 
  def product_params
    params.permit(:name, :image_url, :description, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    redirect_to root_path if current_user.present?
  end

  def create 
    user = User.create(user_params)
    session[:current_user] = user
    redirect_to root_path
  end

  def sign_out 
    session[:current_user] = nil
    redirect_to root_path
  end

  private 

  def user_params
    params.permit(:email, :password, :confirm_password)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_orders_helper.rb
module UserOrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreTesting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="<%= controller_name %>">
        <div class="login-btn-container">
          <% if session[:current_user].present? %>
            <%= link_to "My cart", orders_path %>
            <%= link_to "Sign out", "/sessions/sign_out", method: :delete  %>
          <%else%>
          <%= current_page?(new_session_path) ? "" : link_to("Sign in", new_session_path) %>
          <% end %>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<div class="product-form">
  <h3 class="product-form-title">Add new product</h3>
  <%= form_with model: @product,  url: products_path, method: :post do |form|%>
  <div class="form-control">
     <%= form.label :name, "Product name" %>
     <%= form.text_field :name %>
  </div>
   <div class="form-control">
     <%= form.label :image_url, "Product image url" %>
     <%= form.text_field :image_url %>
  </div>
   <div class="form-control">
     <%= form.label :price, "Product price" %>
     <%= form.text_field :price %>
  </div>
   <div class="form-control">
     <%= form.label :description, "Product description" %>
     <%= form.text_area :description %>
  </div>
  <div class="button-container">
   <%= form.submit "Submit" %>
  </div>
  <%end%>
</div>

app/views/products/index.html.erb
<% if !@products.size.zero?  %>
<div class="add-new-product-btn__container">
  <%= link_to "Add new product", new_product_path, class: "add-new-btn" %> 
<div>
<ul class="products-list">
  <% @products.each do |product| %>
  <li class="product <%= cycle("even", "odd")%> product-<%= product.id %>">
    <span class="product-name"> <%= product.name%></span>
    <p class="product-desc"> <%= product.description%></p>
    <p class="product-price">Price:  <%= product.price %></p>
      <%= link_to "Add to cart", edit_product_path(product) %>
      <%= link_to "Edit", edit_product_path(product) %>
      <%= link_to "Destroy", product_path(product), method: :delete %>
  </li>
<% end %>
</ul>
<% else %>
<div class="products-not-found">
  <h3 class="product-not-found__note">Products not found. Please add new product by clicking on button below.</h3>
  <%= link_to "Add new product", new_product_path, class: "add-new-btn" %> 
</div>
<% end %>

app/views/products/new.html.erb
<div class="product-form">
  <h3 class="product-form-title">Add new product</h3>
  <%= form_with model: @product,  url: products_path, method: :post do |form|%>
  <div class="form-control">
     <%= form.label :name, "Product name" %>
     <%= form.text_field :name %>
  </div>
   <div class="form-control">
     <%= form.label :price, "Product price" %>
     <%= form.text_field :price %>
  </div>
   <div class="form-control">
     <%= form.label :image_url, "Product image url" %>
     <%= form.text_field :image_url %>
  </div>
   <div class="form-control">
     <%= form.label :description, "Product description" %>
     <%= form.text_area :description, rows: 5 %>
  </div>
  <div class="button-container">
   <%= form.submit "Submit" %>
  </div>
  <%end%>
</div>